version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d

  nlp_app:
    build: .
    restart: on-failure
    ports:
      - "80:80"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - MAX_WORKERS=4
